services:
  fix-my-day:
    build: .
    container_name: fix-my-day
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      EXPO_TOKEN: ${EXPO_TOKEN:-}
      EAS_NO_VCS: "1"
      EAS_LOCAL_BUILD_ARTIFACTS_DIR: /app/build-artifacts
      GRADLE_USER_HOME: /root/.gradle
      REACT_NATIVE_PACKAGER_HOSTNAME: localhost
      CHOKIDAR_USEPOLLING: "true"
      BROWSER: none
    ports:
      - "8082:8081"
      - "19100:19000"
      - "19101:19001"
      - "19102:19002"
    stdin_open: true
    tty: true
    volumes:
      - expo-home:/root/.expo
      - eas-home:/root/.eas
      - gradle-cache:/root/.gradle
      - build-artifacts:/app/build-artifacts

volumes:
  expo-home:
  eas-home:
  gradle-cache:
  build-artifacts:
